spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: the-family-guardian, wise-trainer-417001

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    property-naming-strategy: SNAKE_CASE

  ai:
    vertex:
      ai:
        gemini:
          project-id: ${PROJECT_ID}
          location: ${LOCATION}

firebase:
  admin-key-path: ${FIREBASE_ADMIN_KEY_DIR}/${FIREBASE_ADMIN_KEY_NAME}
  app-name: ${FIREBASE_APP_NAME}

google:
  application:
    credentials: ${GOOGLE_APPLICATION_CREDENTIALS}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}

bank:
  company-name: ${COMPANY_AUTH_NAME}
  key:
    user: ${USER_KEY}
    api: ${API_KEY}
